PUT http://127.0.0.1:8000/api/employees/3
Content-Type: application/json
Accept: application/json

{
    "emp_no": 1,
    "birth_date": "1987-11-21",
    "first_name": "S",
    "last_name": "W",
    "gender": "m",
    "hire_date": "2022-02-11"
}


